### ISSUE TITLE
Issues with 1.0.2.exe 

### ISSUE THREAD

**Issue by NeoSyther** [HansRandomizer/Resident-Evil-0-Randomizer#4]
When starting the randomizer I did encounter a small issue. It was from within the current release. Not sure if it was from cheat engine itself tho. 

![Screenshot 2023-08-06 091537](https://github.com/HansRandomizer/Resident-Evil-0-Randomizer/assets/140940758/18311d83-5f8e-42d9-8253-e9cf30f07d8f)

**Comment by HansRandomizer** [comment]
The defender warning is due to code from Cheat Engine or code that was bundled when building the binary. It shouldn’t be my code that causes this. I'll try to rebuild it again with fewer dependencies and see if that helps. But keep in mind, Cheat Engine often triggers virus alerts because it modifies programs.

**Comment by NeoSyther** [comment]
Honestly I was thinking the same thing, but the 2 previous versions didn't flag as hard as this. I do know that cheat engine in itself has a low danger, but I'm not sure what could have specifically caused it to spike like that. This being from 1.0.0 and 1.0.1 below.  
 
![image](https://github.com/HansRandomizer/Resident-Evil-0-Randomizer/assets/140940758/7965f4ce-4752-40ae-a3fb-efaf72ec11d3)

![image](https://github.com/HansRandomizer/Resident-Evil-0-Randomizer/assets/140940758/b4a72cd5-3cc1-43bd-a72e-1de8ba518e4a)

**Comment by HansRandomizer** [comment]
The alert you saw from Windows Defender was a false positive due to an bundled DLL. It should not appear again but there is always a chance to get an anti virus alert. 

The software is built on the open source software Cheat Engine (https://github.com/cheat-engine/cheat-engine), which sometimes gets mistakenly flagged. 

This is mainly because Cheat Engine works by altering existing programs through code injection, which can resemble a potential security concern. This has been an issue since 2006 but I doubt the devs will be able (neither willing....) to do something about it (https://forum.cheatengine.org/viewtopic.php?t=24363)
